# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imageName: 'jivak1/python-docker-managment-tool'
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Push
  displayName: Build and Push Docker image
  pool:
    name: AgentPool
  jobs:
  - job: Build_and_Push
    displayName: Build and Push Docker image
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: DockerHubConnection  
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
        
    - script: docker images
      displayName: List Docker images
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        command: push
        repository: '$(imageName)'
        tags: |
           $(tag)

