# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Push
  displayName: Build and Push Docker image
  jobs:
  - job: Build_and_Push
    displayName: Build and Push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        repository: jivak1/python-docker-managment-tool
        tags: |
          $(tag)
