apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30031
  type: NodePort
