apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app.kubernetes.io/instance: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30020  
  type: NodePort