apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
  - port: metrics
    interval: 15s
