apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 9090
      nodePort: 30030
  type: NodePort
